name: My First Workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Action
        run: echo "Hello, World!"
